### ISSUE TITLE
when using RequestCookieJar instead of cookies, the post "cookie" argument was not replaced to jar

### ISSUE THREAD

**Issue by Sduby22** [yaronav/fiddlerRequestify#1]
sorry for bad English,please take a look at the screenshot
![Snipaste_2019-11-05_21-59-45](https://user-images.githubusercontent.com/29040696/68214152-df5ec800-0017-11ea-9d10-f64f36db4634.png)

**Comment by yaronav** [comment]
Thanks!
Fixed
